import pytest
import numpy as np
from unittest.mock import MagicMock, mock_open, patch #empty shell, reading data, swaps a real python function w/ a fake one
from pathlib import Path
import io
from ct_character.Exciton import ExcitonData, Configuration
from ct_character.Shape import EllipticalCylinder
from ct_character.IOHandler import IOHandler

# --- Fake File data
# A minimal valid .cube file string for testing.
# Header: 2 atoms, Origin at (0,0,0)
# Grid: 2x2x2 (8 pixels total). Step size 0.5
FAKE_CUBE_CONTENT = """Start of Cube File
Generated by TestSuite
    2    0.000000    0.000000    0.000000
    2    0.500000    0.000000    0.000000
    2    0.000000    0.500000    0.000000
    2    0.000000    0.000000    0.500000
    6    1.000000    0.100000    0.100000    0.100000
    1    1.000000    0.900000    0.900000    0.900000
 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0
"""

# Shape params
SHAPE_PARAMS = {"axis_a": 10.0, "axis_b": 5.0, "length_c": 20.0}

def test_read_cube_good_path():
    """ Test 1: Assuming the file is perfect, does it parse the Lattice and Atoms correctly?"""

    # We mock 'open' so Python reads our string variable instead of disk (it doesn't look for
    # a file in the same folder
    with patch("builtins.open", mock_open(read_data = FAKE_CUBE_CONTENT)):
        # We mock Path.exists to return False (This forces it to read text and ignore the cache
        # aka we pretend the file isn't there)
        with patch("pathlib.Path.exists", return_value=False):
            # We mock np.save to prevent it from actually writing a .npy file
            with patch("numpy.save") as mock_save:

                config, data = IOHandler().read_cube(filename="dummy.cube", shape_params=SHAPE_PARAMS)


    # Check 1: Grid Dimensions
    assert config.grid_shape == (2,2,2)

    # Check 2: Lattice Vector Calculations
    # Files says: Step=0.5, Count=2. -> Total Length should be 1.0
    expected_lattice = np.array([[1.0, 0.0, 0.0],
                                 [0.0, 1.0, 0.0],
                                 [0.0, 0.0, 1.0]])
    np.testing.assert_allclose(config.lattice_vectors, expected_lattice)

    # Check 3: Data Parsing
    # The string has 1.0 to 8.0
    # We verify the first and last voxels
    assert data.density[0,0,0] == 1.0
    assert data.density[1,1,1] == 8.0


def test_broken_file_structure():
    """
    Scenario: The file ends abruptly (header exists, data missing).
    Goal: Verify it crashes gracefully with a specific error.
    """
    # A broken file string (Missing the grid definitions)
    BAD_CONTENT = """Start
    Generated by Crash
    2    0.0    0.0    0.0
    """

    with patch("builtins.open", mock_open(read_data=BAD_CONTENT)):
        with patch("pathlib.Path.exists", return_value=False):
            # We expect an IndexError or ValueError when splitting lines
            with pytest.raises((IndexError, ValueError)):
                IOHandler.read_cube("broken.cube", SHAPE_PARAMS)